In [1]:
# 1. confirm both files load
import polars as pl

df = pl.read_parquet("../../data/clean/flights_clean.parquet")
throughput = pl.read_parquet("../../data/clean/airport_throughput.parquet")

# only collect when needed
print(df.shape)
print(throughput.shape)

# 2. check top 10 airports have enough data
throughput.group_by("DEST").agg(
    pl.len().alias("slot_count")
).sort("slot_count", descending=True).head(10)

# 3. check non-COVID data only
throughput.filter(pl.col("COVID_FLAG") == 0)["DEST"].value_counts().sort("count", descending=True).head(10)

(2920860, 33)
(2288702, 11)

shape: (10, 2)
┌──────┬───────┐
│ DEST ┆ count │
│ ---  ┆ ---   │
│ str  ┆ u32   │
╞══════╪═══════╡
│ ATL  ┆ 49343 │
│ ORD  ┆ 43104 │
│ DEN  ┆ 40460 │
│ DFW  ┆ 39019 │
│ LAX  ┆ 38072 │
│ LAS  ┆ 34118 │
│ CLT  ┆ 32401 │
│ PHX  ┆ 32342 │
│ LGA  ┆ 31826 │
│ SEA  ┆ 30919 │
└──────┴───────┘

In [9]:
throughput.select(
    pl.col("arrivals").max().alias("max_arrivals"),
    pl.col("arrivals").mean().alias("mean_arrivals"),
    pl.col("arrivals").median().alias("median_arrivals")
)

shape: (1, 3)
┌──────────────┬───────────────┬─────────────────┐
│ max_arrivals ┆ mean_arrivals ┆ median_arrivals │
│ ---          ┆ ---           ┆ ---             │
│ u32          ┆ f64           ┆ f64             │
╞══════════════╪═══════════════╪═════════════════╡
│ 13           ┆ 1.276208      ┆ 1.0             │
└──────────────┴───────────────┴─────────────────┘

In [10]:
throughput.null_count()

shape: (1, 11)
┌──────┬──────┬──────────┬─────────────────┬───┬──────┬────────────┬────────────┬──────────────────┐
│ DEST ┆ date ┆ arr_hour ┆ arr_15min_block ┆ … ┆ year ┆ is_weekend ┆ COVID_FLAG ┆ hist_mean_arriva │
│ ---  ┆ ---  ┆ ---      ┆ ---             ┆   ┆ ---  ┆ ---        ┆ ---        ┆ ls               │
│ u32  ┆ u32  ┆ u32      ┆ u32             ┆   ┆ u32  ┆ u32        ┆ u32        ┆ ---              │
│      ┆      ┆          ┆                 ┆   ┆      ┆            ┆            ┆ u32              │
╞══════╪══════╪══════════╪═════════════════╪═══╪══════╪════════════╪════════════╪══════════════════╡
│ 0    ┆ 0    ┆ 0        ┆ 0               ┆ … ┆ 0    ┆ 0          ┆ 0          ┆ 0                │
└──────┴──────┴──────────┴─────────────────┴───┴──────┴────────────┴────────────┴──────────────────┘